import{a as p,S as H,N as R,P as V,M as K,K as X,i as b,A as G}from"./assets/vendor-CS33OyOw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const i of o)if(i.type==="childList")for(const g of i.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&r(g)}).observe(document,{childList:!0,subtree:!0});function n(o){const i={};return o.integrity&&(i.integrity=o.integrity),o.referrerPolicy&&(i.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?i.credentials="include":o.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function r(o){if(o.ep)return;o.ep=!0;const i=n(o);fetch(o.href,i)}})();const s={burgerBtn:document.querySelector(".header-burger"),closeBtn:document.querySelector(".mobile-menu-close"),mobileMenu:document.querySelector(".mobile-menu"),mobileMenuLinks:document.querySelectorAll(".mobile-menu-link")};function U(){s.mobileMenu.classList.add("is-open"),document.body.classList.add("no-scroll"),s.burgerBtn.setAttribute("aria-expanded","true"),s.mobileMenu.setAttribute("aria-hidden","false"),s.closeBtn.focus()}function v(){s.burgerBtn.focus(),s.mobileMenu.classList.remove("is-open"),document.body.classList.remove("no-scroll"),s.burgerBtn.setAttribute("aria-expanded","false"),s.mobileMenu.setAttribute("aria-hidden","true")}s.burgerBtn.addEventListener("click",U);s.closeBtn.addEventListener("click",v);s.mobileMenuLinks.forEach(e=>{e.addEventListener("click",()=>{v()})});document.addEventListener("keydown",e=>{e.key==="Escape"&&s.mobileMenu.classList.contains("is-open")&&v()});const B=document.querySelector(".feedbacks-content-list"),D=p.create({baseURL:"https://wedding-photographer.b.goit.study/api"}),F=async e=>{try{const t=await D.get("/feedbacks",{params:{limit:9,page:e}});return console.log(t.data),t.data}catch(t){console.log(t)}},W=e=>e.map(t=>` <li class="feedbacks-content-item swiper-slide">
            <div class="feedbacks-content-item-wrapper">
     <p class="feedbacks-content-comment">
          ${t.descr}
          </p>
          <p class="feedbacks-content-names">${t.name}</p>
          </div>
     
        </li>`).join(""),z=async()=>{B.innerHTML="";try{const e=await F(1);B.insertAdjacentHTML("afterbegin",W(e.feedbacks))}catch(e){console.log(e)}};z();new H(".swiper",{modules:[R,V,K,X],slidesPerView:1,spaceBetween:24,speed:2e3,breakpoints:{320:{slidesPerView:1},768:{slidesPerView:3}},mousewheel:{forceToAxis:!0},keyboard:{enabled:!0,onlyInViewport:!0},pagination:{el:".custom-swiper-pagination",type:"bullets",clickable:!0,dynamicBullets:!0},navigation:{nextEl:".custom-swiper-button-next",prevEl:".custom-swiper-button-prev"}});p.defaults.baseURL="https://wedding-photographer.b.goit.study/api";let L=document.querySelector(".portfolio-category-ul"),C=document.querySelector(".gallery"),u=document.querySelector(".progress-label"),k=document.querySelector(".loading"),M=document.querySelector(".show-more"),I=document.querySelector(".loader");L.addEventListener("click",ne);M.addEventListener("click",ie);let h=null,y=null,c=-1,w=0,m=0,d=0,l=0,S=9,O=3;y=L.children[0].children[0];y.style.border="2px solid black";re();P(c,S);function T(){l=0,d=0,w=0,m=0}function _(e){const t=e.map(n=>`<li>
         <button type="button" class="category-btn">${n.category}</button>
       </li>`);L.insertAdjacentHTML("beforeend",t.join(" "))}function J(e){const t=e.map(n=>`<li class="gallery-item" >
           <img class="gallery-image" src="${n.img}" alt="${n.title}" />
        </li>`);C.insertAdjacentHTML("beforeend",t.join(" "))}function $(){C.innerHTML=""}function j(){u.style.visibility="hidden",k.style.visibility="hidden"}function Q(){u.style.visibility="visible",k.style.visibility="visible"}function f(){M.style.visibility="hidden"}function Y(){M.style.visibility="visible"}function Z(){I.style.visibility="visible"}function E(){I.style.visibility="hidden"}function ee(e,t){u.textContent=`Downloaded ${e} from ${t}`,u.style.margin="0 auto",k.value=e/t*100}async function te(){const e={};return(await p.get("/categories",{params:e})).data}async function oe(e,t,n){const r={page:e,limit:n};return t!=""&&(r.categoryId=t),(await p.get("/wedding-photos",{params:r})).data}async function re(){try{h=await te(),_(h)}catch{}}async function P(e,t){let n=e==-1?"":h[e]._id;Z();try{let r=await oe(l+1,n,t);if(l==0&&r.totalItems==0){b.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}l+=1,l==1&&(d=r.totalItems,w=Math.ceil((d-S)/O)+1),m+=r.weddingPhotos.length,J(r.weddingPhotos),E(),ee(m,d),Q(),l<w?Y():(f(),b.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch{b.error({position:"topRight",message:"Something went wrong!"}),$(),T(),j(),f(),E()}}async function ne(e){let t=e.target.parentNode,n=e.currentTarget,r=Array.from(n.children).indexOf(t)-1;c!=r&&(c=r,y.style.border="none",e.target.style.border="2px solid black",y=e.target,T(),$(),f(),j(),await P(c,S))}async function ie(){f(),await P(c,Math.min(d-m,O))}new G(".faq-list",{duration:300,showMultiple:!1,elementClass:"faq-item",triggerClass:"faq-trigger",panelClass:"faq-panel",activeClass:"faq-item--active"});const se=document.querySelector("header"),a={openModalBtn:document.querySelector("[data-modal-open]"),closeModalBtn:document.querySelector("[data-modal-close]"),backdrop:document.querySelector("[data-modal]")};var A,x;a.backdrop&&((A=a.openModalBtn)==null||A.addEventListener("click",ae),(x=a.closeModalBtn)==null||x.addEventListener("click",q),a.backdrop.addEventListener("click",le));function ae(){a.backdrop&&(a.backdrop.classList.remove("is-hidden"),window.addEventListener("keydown",N),document.body.style.overflow="hidden")}function q(){a.backdrop&&(a.backdrop.classList.add("is-hidden"),window.removeEventListener("keydown",N),document.body.style.overflow="",se.style.position="sticky")}function le(e){e.target===e.currentTarget&&q()}function N(e){e.code==="Escape"&&q()}
//# sourceMappingURL=index.js.map
