import{a as u,S as d,N as m,P as p,M as f,K as b,A as g}from"./assets/vendor-Dkcfcb_D.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const o of n.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function l(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(e){if(e.ep)return;e.ep=!0;const n=l(e);fetch(e.href,n)}})();const s={burgerBtn:document.querySelector(".header-burger"),closeBtn:document.querySelector(".mobile-menu-close"),mobileMenu:document.querySelector(".mobile-menu"),mobileMenuLinks:document.querySelectorAll(".mobile-menu-link")};function y(){s.mobileMenu.classList.add("is-open"),document.body.classList.add("no-scroll"),s.burgerBtn.setAttribute("aria-expanded","true"),s.mobileMenu.setAttribute("aria-hidden","false"),s.closeBtn.focus()}function i(){s.burgerBtn.focus(),s.mobileMenu.classList.remove("is-open"),document.body.classList.remove("no-scroll"),s.burgerBtn.setAttribute("aria-expanded","false"),s.mobileMenu.setAttribute("aria-hidden","true")}s.burgerBtn.addEventListener("click",y);s.closeBtn.addEventListener("click",i);s.mobileMenuLinks.forEach(t=>{t.addEventListener("click",()=>{i()})});document.addEventListener("keydown",t=>{t.key==="Escape"&&s.mobileMenu.classList.contains("is-open")&&i()});const c=document.querySelector(".feedbacks-content-list"),w=u.create({baseURL:"https://wedding-photographer.b.goit.study/api"}),h=async t=>{try{const r=await w.get("/feedbacks",{params:{limit:9,page:t}});return console.log(r.data),r.data}catch(r){console.log(r)}},L=t=>t.map(r=>` <li class="feedbacks-content-item swiper-slide">
            <div class="feedbacks-content-item-wrapper">
     <p class="feedbacks-content-comment">
          ${r.descr}
          </p>
          <p class="feedbacks-content-names">${r.name}</p>
          </div>
     
        </li>`).join(""),M=async()=>{c.innerHTML="";try{const t=await h(1);c.insertAdjacentHTML("afterbegin",L(t.feedbacks))}catch(t){console.log(t)}};M();new d(".swiper",{modules:[m,p,f,b],slidesPerView:1,spaceBetween:24,speed:2e3,breakpoints:{320:{slidesPerView:1},768:{slidesPerView:3}},mousewheel:{forceToAxis:!0},keyboard:{enabled:!0,onlyInViewport:!0},pagination:{el:".custom-swiper-pagination",type:"bullets",clickable:!0,dynamicBullets:!0},navigation:{nextEl:".custom-swiper-button-next",prevEl:".custom-swiper-button-prev"}});new g(".faq-list",{duration:300,showMultiple:!1,elementClass:"faq-item",triggerClass:"faq-trigger",panelClass:"faq-panel",activeClass:"faq-item--active"});
//# sourceMappingURL=index.js.map
